# Generated by Django 5.0.6 on 2024-05-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_birthday_images_alter_birthday_birthday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='images',
            new_name='image',
        ),
    ]
