# Generated by Django 5.0.6 on 2024-05-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_birthday_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={'verbose_name': 'Дни рождения'},
        ),
    ]
